# Generated by Django 4.0.3 on 2022-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_remove',
            field=models.BooleanField(default=False),
        ),
    ]
