# Generated by Django 4.0.3 on 2022-03-23 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_logtype_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='account_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='account_is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
