# Generated by Django 4.0.3 on 2022-03-23 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_customerprofile_account_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogType',
            new_name='BusinessType',
        ),
        migrations.CreateModel(
            name='RemoteAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_account_business', to='Account.businesstype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_remote_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
