# Generated by Django 4.0.3 on 2022-04-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0010_producttype_journalproducttype_journal_products'),
        ('Account', '0009_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upload', to='Paper.submit'),
        ),
    ]
