# Generated by Django 4.0.3 on 2022-04-12 06:14

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_upload_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=Account.models.user_directory_path),
        ),
    ]
