# Generated by Django 4.0.3 on 2022-04-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_upload',
            field=models.BooleanField(default=False),
        ),
    ]
