# Generated by Django 4.0.3 on 2022-04-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_alter_membership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.unit'),
        ),
    ]
