# Generated by Django 4.0.3 on 2022-04-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_user_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
