# Generated by Django 4.0.4 on 2022-06-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='unit',
            new_name='department',
        ),
    ]
