# Generated by Django 4.0.4 on 2022-06-13 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_rename_unit_customerprofile_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remoteaccount',
            unique_together={('user', 'type')},
        ),
    ]
