# Generated by Django 4.0.4 on 2022-06-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0041_alter_journal_guide_url_alter_journal_logo_url'),
        ('Account', '0023_alter_remoteaccount_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='account_is_active',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='account_is_staff',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='remoteaccount',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_journal', to='Paper.journal'),
        ),
        migrations.AlterField(
            model_name='remoteaccount',
            name='host',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
