# Generated by Django 4.0.4 on 2022-06-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0024_remove_customerprofile_account_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remoteaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='remoteaccount',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_remote_account', to='Account.customerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='remoteaccount',
            unique_together={('profile', 'type', 'username')},
        ),
        migrations.RemoveField(
            model_name='remoteaccount',
            name='user',
        ),
    ]
