# Generated by Django 4.0.4 on 2022-06-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0025_alter_remoteaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
    ]
