# Generated by Django 4.0.4 on 2022-06-15 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0026_remove_customerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteaccount',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_business', to='Account.businesstype'),
        ),
    ]
