# Generated by Django 4.0.4 on 2022-06-18 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0027_alter_remoteaccount_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='is_view',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='to',
        ),
        migrations.AddField(
            model_name='notice',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
