# Generated by Django 4.0.4 on 2022-06-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0028_rename_is_view_notice_is_read_remove_notice_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.JSONField(null=True),
        ),
    ]
