# Generated by Django 4.0.4 on 2022-08-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0033_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
