# Generated by Django 4.0.4 on 2022-05-02 10:30

import Paper.helper
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paper', '0039_remove_resource_file_lists'),
        ('Account', '0018_alter_log_type_alter_remoteaccount_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=Paper.helper.resource_upload_path)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_upload_file', to='Paper.resource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_business_type', to='Account.businesstype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
