# Generated by Django 4.0.3 on 2022-03-24 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0003_orderstatuslog_order_status_logs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('nicename', models.CharField(max_length=80)),
                ('iso3', models.CharField(max_length=2, null=True)),
                ('numcode', models.IntegerField(max_length=6, null=True)),
                ('phonecode', models.SmallIntegerField(max_length=6)),
            ],
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewType',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='review',
            new_name='review_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='file_lists',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('reason', models.CharField(max_length=255, null=True)),
                ('appellation', models.CharField(choices=[('Dr', 'Doctor'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Professor', 'professor')], default='Mr', max_length=12)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Paper.country')),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submit_author', to='Paper.submit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
