# Generated by Django 4.0.3 on 2022-03-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0005_alter_country_iso3'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer')], default='author', max_length=12),
        ),
    ]
