# Generated by Django 4.0.3 on 2022-03-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0006_author_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='nicename',
            new_name='nice_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='numcode',
            new_name='num_code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='phonecode',
            new_name='phone_code',
        ),
        migrations.AddField(
            model_name='submit',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submit_article', to='Paper.article'),
        ),
        migrations.AddField(
            model_name='submit',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submit_journal', to='Paper.journal'),
        ),
        migrations.AddField(
            model_name='submit',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='major',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='upload_files',
            field=models.JSONField(null=True),
        ),
    ]
