# Generated by Django 4.0.3 on 2022-04-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0007_rename_nicename_country_nice_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='eissn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviewtype',
            name='json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='num_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.SmallIntegerField(),
        ),
    ]
