# Generated by Django 4.0.3 on 2022-04-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0008_category_frequency_journal_eissn_reviewtype_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='country_journal', to='Paper.country')),
            ],
        ),
        migrations.CreateModel(
            name='JournalFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='frequency_journal', to='Paper.frequency')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='countries',
            field=models.ManyToManyField(blank=True, through='Paper.JournalCountry', to='Paper.country'),
        ),
        migrations.AddField(
            model_name='journal',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='frequency',
            field=models.ManyToManyField(blank=True, through='Paper.JournalFrequency', to='Paper.frequency'),
        ),
        migrations.AddField(
            model_name='journal',
            name='impact_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='journal',
            name='issues_per_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='open_access',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='start_year',
            field=models.SmallIntegerField(default=1990),
        ),
        migrations.AddField(
            model_name='journal',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='journalfrequency',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_frequency', to='Paper.journal'),
        ),
        migrations.AddField(
            model_name='journalcountry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_country', to='Paper.journal'),
        ),
    ]
