# Generated by Django 4.0.3 on 2022-04-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0010_producttype_journalproducttype_journal_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_journal', to='Paper.category')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='categories',
            field=models.ManyToManyField(blank=True, through='Paper.JournalCategory', to='Paper.category'),
        ),
        migrations.AddField(
            model_name='journalcategory',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_category', to='Paper.journal'),
        ),
    ]
