# Generated by Django 4.0.3 on 2022-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0011_journalcategory_journal_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
