# Generated by Django 4.0.3 on 2022-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0012_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
