# Generated by Django 4.0.3 on 2022-04-19 10:23

import Paper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0014_alter_country_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='logo_url',
            field=models.ImageField(null=True, upload_to=Paper.models.publisher_logo_path),
        ),
    ]
