# Generated by Django 4.0.3 on 2022-04-20 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0015_alter_publisher_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='Paper.JournalCategory', to='Paper.category'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, through='Paper.JournalCountry', to='Paper.country'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='frequency',
            field=models.ManyToManyField(blank=True, null=True, through='Paper.JournalFrequency', to='Paper.frequency'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='Paper.JournalProductType', to='Paper.producttype'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_publisher', to='Paper.publisher'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='review_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_review_method', to='Paper.reviewtype'),
        ),
    ]
