# Generated by Django 4.0.3 on 2022-04-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0016_alter_journal_categories_alter_journal_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='frequency',
        ),
        migrations.AddField(
            model_name='journal',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_frequency', to='Paper.frequency'),
        ),
        migrations.DeleteModel(
            name='JournalFrequency',
        ),
    ]
