# Generated by Django 4.0.3 on 2022-04-20 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0018_alter_journal_categories_alter_journal_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_journal', to='Paper.category'),
        ),
        migrations.AlterField(
            model_name='journalcategory',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_category', to='Paper.journal'),
        ),
        migrations.AlterField(
            model_name='journalcountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_journal', to='Paper.country'),
        ),
        migrations.AlterField(
            model_name='journalcountry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_country', to='Paper.journal'),
        ),
        migrations.AlterField(
            model_name='journalproducttype',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_product', to='Paper.journal'),
        ),
        migrations.AlterField(
            model_name='journalproducttype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_journal', to='Paper.producttype'),
        ),
    ]
