# Generated by Django 4.0.3 on 2022-04-20 09:16

import Paper.helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paper', '0019_alter_journalcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=Paper.helper.submit_upload_path)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_upload_paper_type', to='Paper.requirement')),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_uploaded_paper', to='Paper.submit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
