# Generated by Django 4.0.3 on 2022-04-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0020_submit_user_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='upload_files',
        ),
    ]
