# Generated by Django 4.0.3 on 2022-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0021_remove_submit_upload_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
