# Generated by Django 4.0.3 on 2022-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0022_alter_submit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submit',
            name='keywords',
            field=models.TextField(),
        ),
    ]
