# Generated by Django 4.0.3 on 2022-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0023_alter_submit_abstract_alter_submit_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
