# Generated by Django 4.0.3 on 2022-04-21 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paper', '0024_alter_submit_abstract_alter_submit_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='contactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submit_contactor', to=settings.AUTH_USER_MODEL),
        ),
    ]
