# Generated by Django 4.0.3 on 2022-04-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0025_submit_contactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submit_author', to='Paper.submit'),
        ),
    ]
