# Generated by Django 4.0.3 on 2022-04-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0026_alter_author_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='submit',
        ),
    ]
