# Generated by Django 4.0.3 on 2022-04-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0027_remove_uploadfile_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submit_upload_file', to='Paper.submit'),
        ),
    ]
