# Generated by Django 4.0.3 on 2022-04-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0030_submit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='codename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
