# Generated by Django 4.0.3 on 2022-04-27 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0031_status_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Paper.country'),
        ),
        migrations.AlterField(
            model_name='author',
            name='submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submit_author', to='Paper.submit'),
        ),
    ]
