# Generated by Django 4.0.4 on 2022-04-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0035_orderstatuslog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderstatuslog',
            unique_together={('order', 'status')},
        ),
    ]
