# Generated by Django 4.0.4 on 2022-04-30 22:19

import Paper.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0036_resource_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='censor_file',
            field=models.FileField(null=True, upload_to=Paper.helper.censor_file_path),
        ),
        migrations.AddField(
            model_name='order',
            name='download_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_censor_download',
            field=models.BooleanField(default=False),
        ),
    ]
