# Generated by Django 4.0.4 on 2022-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0037_order_censor_file_order_download_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='content',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='is_download',
            new_name='is_upload',
        ),
        migrations.AddField(
            model_name='resource',
            name='is_allow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
