# Generated by Django 4.0.4 on 2022-05-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0038_rename_content_resource_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file_lists',
        ),
    ]
