# Generated by Django 4.0.4 on 2022-06-03 08:32

import Paper.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0039_remove_resource_file_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='guide_url',
            field=models.FileField(max_length=500, null=True, upload_to=Paper.helper.journal_resource_path),
        ),
    ]
