# Generated by Django 4.0.4 on 2022-06-03 09:06

import Paper.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0040_alter_journal_guide_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='guide_url',
            field=models.FileField(max_length=1024, null=True, upload_to=Paper.helper.journal_resource_path),
        ),
        migrations.AlterField(
            model_name='journal',
            name='logo_url',
            field=models.ImageField(max_length=1024, null=True, upload_to=Paper.helper.journal_resource_path),
        ),
    ]
