# Generated by Django 4.0.4 on 2022-06-16 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paper', '0041_alter_journal_guide_url_alter_journal_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_dealer', to=settings.AUTH_USER_MODEL),
        ),
    ]
