# Generated by Django 4.0.4 on 2022-06-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0042_resource_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dealer',
        ),
    ]
