# Generated by Django 4.0.4 on 2022-07-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0044_resource_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('submission', 'Submission'), ('request', 'Request')], default='submission', max_length=12),
        ),
    ]
