# Generated by Django 4.0.4 on 2022-08-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0049_exchange_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='codename',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('submission', 'Submission'), ('request', 'Request'), ('resource upload', 'Resource Upload'), ('exchange', 'Exchange')], default='submission', max_length=64),
        ),
    ]
