# Generated by Django 4.0.4 on 2022-08-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0050_alter_status_codename_alter_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='censor_document',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='censor_input_info',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='censor_output_info',
            field=models.JSONField(null=True),
        ),
    ]
