# Generated by Django 4.0.4 on 2022-08-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0051_order_censor_document_order_censor_input_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_country', to='Paper.country'),
        ),
    ]
