# Generated by Django 4.0.4 on 2022-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0053_alter_frequency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192, null=True)),
                ('code', models.CharField(max_length=192, unique=True)),
            ],
        ),
    ]
