# Generated by Django 4.0.4 on 2022-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0054_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
