# Generated by Django 4.0.4 on 2022-10-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0056_journallanguage_remove_journal_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='data_identifier',
            field=models.IntegerField(null=True),
        ),
    ]
