# Generated by Django 4.0.4 on 2022-11-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0057_exchange_data_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='outer_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
