# Generated by Django 4.0.4 on 2022-11-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0058_exchange_outer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='outer_dealer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='outer_dealer_real_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
