# Generated by Django 4.0.4 on 2022-11-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0059_exchange_outer_dealer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='input_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='input_size',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
